[package]
name = "jstprove-onnx"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
prost = "0.13"
anyhow = "1"
serde = { version = "1", features = ["derive"] }

[build-dependencies]
prost-build = "0.13"

[dev-dependencies]
tempfile = "3"
