repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: detect-private-key

  # Python formatting with black
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--check]

  # Python linting with ruff (comprehensive)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [
          --fix,
          --exit-non-zero-on-fix,
          --select=ALL,  # Enable all rules for local checks
          --ignore=D,    # Ignore documentation warnings
          '--per-file-ignores=python/tests/**.py:S101', # allows assert statements in tests
          '--per-file-ignores=python/tests/**.py:T201', # Allows print lines in tests
          '--per-file-ignores=python/tests/**.py:F811', # Allows redefinition of unused name in tests (For fixtures which skip tests)
          '--per-file-ignores=python/tests/**.py:PLR0913', # Allows more arguments in function definition in tests (Fixtures etc.)
          '--per-file-ignores=python/tests/**.py:SLF001', # Allows private members to be accessed in tests (_file_info, _compile_preprocessing)
          '--per-file-ignores=python/tests/**.py:ARG001', # Allows unused function arguments in tests (used for mocked variables)
          '--per-file-ignores=python/core/model_processing/onnx_custom_ops/**.py:PLR0913', # Allows more arguments in onnx_custom_ops, due to necessity of integration BLE001
          '--per-file-ignores=python/**.py:BLE001', # Allows blind exception handling

        ]

  # Rust formatting and linting
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ['--manifest-path=./Cargo.toml', '--all', '--', '--check']
      - id: clippy
        args: [
          '--manifest-path=./Cargo.toml',
          '--all',
          '--',
          -W, 'clippy::all',
          -W, 'clippy::pedantic',
          -D, warnings,
        ]

  # Dependency checks
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
      - id: poetry-check  # Validates pyproject.toml
      - id: poetry-lock   # Updates poetry.lock if needed
