[package]
name = "babybear"
version.workspace = true
edition.workspace = true

[dependencies]

arith.workspace = true
serdes.workspace = true

ark-std.workspace = true
ethnum.workspace = true
rand.workspace = true


[[bench]]
name = "babybear"
harness = false

[dev-dependencies]
criterion.workspace = true
