[package]
name = "jstprove-direct-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
expander_compiler.workspace = true
arith.workspace = true
ethnum.workspace = true

[dev-dependencies]
gkr_engine.workspace = true
