[package]
name = "jstprove-pyo3"
version = "0.1.0"
edition = "2021"

[lib]
name = "jstprove"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
jstprove-remainder = { path = "../jstprove_remainder" }
serde_json = "1"
anyhow = "1"
