# This workflow will install Python dependencies, run tests and lint with a single version of Python
# TODO: Add a matrix of Python Versions if we want to support cross-compatibility
# TODO: Create tests for different sources such as : ["class", "pytorch", "onnx"]
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: JSTProve Python Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"  #Should we specify more versions?
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install OMPI
      run: |
        apt-get update && apt-get install -y \
          libopenmpi-dev \
          pkg-config \
          libclang-dev \
          clang
    - name: Test Doom Model #TODO: Have a standardized model to run from, multiple sources (other than ONNX)?
      run: |
        mkdir -p report
        pytest --model doom --source onnx --html=report/report.html

    - name: Upload Pytest HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-html-report
        path: report

