# TODO: Add a matrix of Python Versions if we want to support cross-compatibility

name: Unit, Integration Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  #Should we specify more versions?
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Install OMPI
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libopenmpi-dev \
            pkg-config \
            libclang-dev \
            clang \
            openmpi-bin \
      
      - name: Run Unit Tests
        run: |
          mkdir -p report
          pytest --unit --html=report/unit_tests.html
      
      - name: Run Integration Tests
        run: |
          mkdir -p report
          pytest --integration --html=report/integration_tests.html
      
      - name: Upload Pytest HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report