# TODO: Add a matrix of Python Versions if we want to support cross-compatibility
# TODO: Create tests for different sources such as : ["class", "pytorch", "onnx"]

name: Unit, Integration Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  formatting-and-linting:
    name: Check Formatting and Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for file change detection
      
      # Setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      # Setup Rust
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-03-27
          components: rustfmt, clippy
          override: true
      
      # Run formatters and linters
      - name: Install pre-commit
        run: pip install pre-commit
      
      # Get latest version
      - name: Update Pre-commit
        run: pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.py
            **/*.rs
          
      - name: Run pre-commit on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files ${{ steps.changed-files.outputs.all_changed_files}}
        
      # Additional Rust checks (easier to just run on all)
      - name: Run cargo fmt check
        run: cargo fmt --all -- --check
        
      - name: Run cargo clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  build:
    needs: formatting-and-linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  #Should we specify more versions?
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Install OMPI
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libopenmpi-dev \
            pkg-config \
            libclang-dev \
            clang \
            openmpi-bin \
      
      - name: Run Unit Tests
        run: |
          mkdir -p report
          pytest --unit --html=report/unit_tests.html
      
      - name: Run Integration Tests
        run: |
          mkdir -p report
          pytest --integration --html=report/integration_tests.html
      
      - name: Upload Pytest HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report