name: Unit, Integration Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --group test

      - name: Install OMPI
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libopenmpi-dev \
            pkg-config \
            libclang-dev \
            clang \
            openmpi-bin \

      - name: Run Unit Tests
        run: |
          mkdir -p report
          uv run pytest --unit --html=report/unit_tests.html

      - name: Run Integration Tests
        run: |
          mkdir -p report
          uv run pytest --integration --html=report/integration_tests.html

      - name: Upload Pytest HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report
